### PR TITLE
TQVaultAE Json file full support

### PR DESCRIPTION
**Pull request by hguy**
Hi @Malgardian,

It's officially done !

You just have to build it with Visual Studio 2022 and deliver.

Ask if you have questions.

hguy.

### CODE REVIEW

**Comment by hguy** [comment]
This fix #28.

**Comment by hguy** [comment]
i did normalize the repository and the solution and updated the changelog.txt

image
image

**Comment by Malgardian** [comment]
Thanks for your work. Sadly, I haven't had time to look through it yet. But I hope to be able to get that done over the next weeks. One question, though: Why "Dto"? What does it stand for?

**Comment by hguy** [comment]
> Thanks for your work. Sadly, I haven't had time to look through it yet. But I hope to be able to get that done over the next weeks. 

If you want, i can produce a pre-release on my branch with a zip for download, and community feedback.

> One question, though: Why "Dto"? What does it stand for?

Here's a good definition.
https://stackoverflow.com/questions/1051182/what-is-a-data-transfer-object-dto

**Comment by Malgardian** [comment]
> > Thanks for your work. Sadly, I haven't had time to look through it yet. But I hope to be able to get that done over the next weeks.
> 
> If you want, i can produce a pre-release on my branch with a zip for download, and community feedback.
Nah, it's fine. I have a few things of my own I want to add before a release is going to happen. I've set aside some time next weekend to do all that. 

> > One question, though: Why "Dto"? What does it stand for?
> 
> Here's a good definition. https://stackoverflow.com/questions/1051182/what-is-a-data-transfer-object-dto
Ah, right. Makes sense now.

**Pull request merged**
